server:
  port: 8088
  servlet:
    context-path: /neusoft
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/haha?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static
mybatis:
  config-location: mybatis-config.xml
  mapper-locations: /mapper/**.xml
  type-aliases-package: com.entity

